// Phase 4 Step 6 — events.jsonl substrate (Rust host single-writer).
//
// Append-only audit log of state-changing events at
// `<cwd>/.opencrab/teams/<team_id>/events.jsonl`. Step 1 mkdirs the
// `teams/<team_id>/` parent + touches an empty `events.jsonl`; Step 6
// only ever appends. Reader / consumer wires (P5 memory_search,
// P7 UI surface, P8 supervisor) land in later phases — Step 6 ships
// the substrate and a single read-only `list_team_events` helper.
//
// Constraints (locked at Step 6):
//   * **Single writer.** Only the Rust host emits. Sidecar / other
//     processes never touch this file; cross-process serialization is
//     out of scope (single-instance Phase 4 assumption).
//   * **Append-only.** Never truncate, overwrite, or splice. The file is
//     allowed to grow without bound — rotation is a P5+ concern.
//   * **Row atomicity.** Each event = exactly one line. We hold a
//     `Mutex<File>` for the duration of a `writeln!` + `flush` so
//     in-process Tokio tasks can never interleave bytes within a line.
//     Cross-process safety relies on POSIX `O_APPEND` (single writer
//     assumption above keeps us inside the regime where this matters).
//   * **No fsync per emit.** events.jsonl is NOT the source of truth
//     (the `tasks` table is). Losing the tail to a crash is acceptable;
//     paying an fsync per row is not.
//   * **schemaVersion = 1.** Matches the Phase 3 `tasks-proposed` event
//     payload version policy; bumping requires a documented migration.
//
// Schema is forward-looking — 8 task-lifecycle variants are defined even
// though Phase 3 only fires three of them (`TaskProposed`,
// `TaskApproved`, `TaskRejected`). The remaining five (`TaskStarted`,
// `TaskBlocked`, `TaskUnblocked`, `TaskDone`, `TaskArchived`) emit
// whenever the generic `transition_task` Tauri command exercises them;
// P5/P7/P8 will wire production callers.

mod commands;
mod log;
mod types;

#[cfg(test)]
mod tests;

// Re-export `*` so Tauri's `__cmd__*` companion symbols (generated by
// `#[tauri::command]`) are visible to `invoke_handler!` in lib.rs.
pub(crate) use commands::*;
pub(crate) use log::{get_or_create_event_log, EventLog};
pub(crate) use types::{event_for_transition, TeamEventBody};
