#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
corpus_tool.py — generator + offline verifier for the V2 memory test corpus.

WHY THIS EXISTS
---------------
The ground_truth.yaml of every case carries an `expected_ingest` block whose
`kept_line_nos` / `dropped_line_nos` / `boundary_line_nos` / `raw_event_count`
must match, byte-for-byte, what the Rust S2 ingester + `parse_line` would
classify. Hand-authoring escaped JSON (Chinese, emoji, stringified tool args,
multi-line codex tool-output envelopes) with correct line bookkeeping is
error-prone. So:

  * The rollout-*.jsonl bytes are GENERATED here, from per-case line specs.
  * Every synthesized line is SELF-CHECKED against a faithful Python port of
    backend.rs `parse_line` (the port below mirrors the source verbatim — see
    _anchors/anchors.md §1). A shape mistake fails generation loudly.
  * `expected_ingest` is derived from the generated bytes (truth) and patched
    into each hand-authored ground_truth.yaml (`verify --fix`), so the
    mechanical block is never transcribed by hand.

OWNERSHIP / WORKFLOW
--------------------
  * rollout-*.jsonl   -> GENERATED. Edit the case spec in this file, re-run
                        `gen`. Do not hand-edit the .jsonl.
  * ground_truth.yaml -> HAND-AUTHORED. This tool only ever rewrites the single
                        region between the two `expected_ingest` sentinel
                        comment lines (via `verify --fix`); every semantic block
                        (expected_distill / expected_search / consolidation) is
                        left untouched. Safe to hand-tune per the spec §7 loop.

The S3/S4/S5 *semantic* assertions need a live LLM/embedder and are the
corpus-runner harness's job; this tool verifies only the offline-knowable S2
mechanics + prints the rendered transcript so you can eyeball what the LLM sees.

USAGE
-----
  python3 corpus_tool.py gen                 # (re)write every case's rollout jsonl + print transcripts
  python3 corpus_tool.py verify              # check each yaml's expected_ingest against its jsonl
  python3 corpus_tool.py verify --fix        # rewrite the expected_ingest region from jsonl truth
  python3 corpus_tool.py transcript C012     # dump rendered transcript + segments for one case

stdlib only. No third-party deps (no PyYAML — the yaml region is plain text).
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CASES_DIR = os.path.normpath(os.path.join(HERE, "..", "cases"))

ING_START = "# >>> expected_ingest (generated by corpus_tool.py — run `verify --fix`) >>>"
ING_END = "# <<< expected_ingest <<<"

DISTILL_MAX_TRANSCRIPT_CHARS = 48_000  # anchors §0.3 — Phase 1 cases stay well under this


# =====================================================================
# 1. Faithful port of backend.rs parse_line / render_item / segment_thread
#    (anchors.md §1, §2). Returns ('kept'|'boundary'|'dropped', rendered).
#    `rendered` is the transcript line for Kept (or None if render_item
#    would skip it), the summary string for Boundary, None for Dropped.
# =====================================================================

def parse_line(payload: str):
    try:
        v = json.loads(payload)
    except Exception:
        return ("dropped", None)
    if not isinstance(v, dict):
        return ("dropped", None)
    top = v.get("type")
    if not isinstance(top, str):
        return ("dropped", None)
    if top == "compacted":
        p = v.get("payload")
        msg = p.get("message") if isinstance(p, dict) else None
        return ("boundary", msg if isinstance(msg, str) else "")
    if top == "response_item":
        return _parse_response_item(v.get("payload"))
    # session_meta / turn_context / event_msg / unknown
    return ("dropped", None)


def _parse_response_item(p):
    if not isinstance(p, dict):
        return ("dropped", None)
    inner = p.get("type")
    if not isinstance(inner, str):
        return ("dropped", None)
    if inner == "message":
        return _parse_message(p)
    if inner == "function_call":
        return _parse_function_call(p)
    if inner == "function_call_output":
        return _parse_function_call_output(p)
    if inner in (
        "local_shell_call",
        "tool_search_call",
        "tool_search_output",
        "custom_tool_call",
        "custom_tool_call_output",
        "web_search_call",
    ):
        return _parse_tool_misc(p, inner)
    # reasoning / compaction / context_compaction / image_generation_call / unknown
    return ("dropped", None)


def _parse_message(p):
    role = p.get("role")
    if not isinstance(role, str):
        return ("dropped", None)
    if role == "developer":
        return ("dropped", None)
    buf = ""
    content = p.get("content")
    if isinstance(content, list):
        for item in content:
            if not isinstance(item, dict):
                continue
            kind = item.get("type")
            if kind in ("input_text", "output_text"):
                txt = item.get("text")
                if isinstance(txt, str):
                    buf += txt
    if buf.strip() == "":
        return ("dropped", None)
    # render_item Message: skip if whitespace-only (already excluded above)
    return ("kept", "{}: {}".format(role.upper(), buf))


def _parse_function_call(p):
    name = p.get("name")
    args = p.get("arguments")
    name = name if isinstance(name, str) else ""
    args = args if isinstance(args, str) else ""
    if name == "" and args == "":
        return ("dropped", None)
    # render_item ToolCall: None when name AND args are both whitespace-only.
    if name.strip() == "" and args.strip() == "":
        return ("kept", None)
    n = name if name != "" else "<unknown>"
    return ("kept", "TOOL CALL {}: {}".format(n, args))


def _parse_function_call_output(p):
    out = p.get("output")
    if isinstance(out, str):
        text = out
    elif isinstance(out, dict):
        if isinstance(out.get("content"), str):
            text = out["content"]
        elif isinstance(out.get("content_items"), list):
            text = "".join(
                it.get("text", "")
                for it in out["content_items"]
                if isinstance(it, dict) and isinstance(it.get("text"), str)
            )
        else:
            text = ""
    else:
        text = ""
    # Always Kept; render_item skips when output is whitespace-only.
    if text.strip() == "":
        return ("kept", None)
    return ("kept", "TOOL RESULT: {}".format(text))


def _parse_tool_misc(p, kind):
    text = None
    for key in ("text", "input", "query", "execution", "content"):
        val = p.get(key)
        if isinstance(val, str) and val != "":
            text = val
            break
    if text is not None and text.strip() != "":
        rendered = "TOOL {}: {}".format(kind.upper(), text)
    else:
        rendered = "[tool: {}]".format(kind)
    return ("kept", rendered)


def segment_thread(lines):
    """lines: list of (line_no:int, payload:str). Mirrors backend.rs:1091-1146.
    Returns list of dicts: {start, end, prior_summary, transcript}."""
    segments = []
    buf = []
    start_line = None
    pending_prior = None
    last_no = None
    for (line_no, payload) in lines:
        last_no = line_no
        if start_line is None:
            start_line = line_no
        cls, rendered = parse_line(payload)
        if cls == "kept":
            if rendered is not None:
                buf.append(rendered)
        elif cls == "boundary":
            segments.append({
                "start": start_line,
                "end": line_no,
                "prior_summary": pending_prior,
                "transcript": "\n".join(buf),
            })
            buf = []
            start_line = None
            pending_prior = rendered  # the boundary summary
        # dropped: nothing
    if start_line is not None:
        end = last_no if last_no is not None else start_line
        segments.append({
            "start": start_line,
            "end": end,
            "prior_summary": pending_prior,
            "transcript": "\n".join(buf),
        })
    return segments


# =====================================================================
# 2. Line builders. Each returns (intended_class, payload_dict).
#    payload_dict is the line WITHOUT the top-level "timestamp" (the
#    writer injects a cosmetic, parser-ignored timestamp per line).
# =====================================================================

DEV_BOILERPLATE = (
    "You are operating in a sandboxed workspace. Tools available: edit, write, "
    "exec_command. Respect the approval policy and never touch files outside the "
    "workspace root. <skills>memory_search, memory_get</skills>"
)


def SM(cwd="/Users/USER/code/PROJECT"):
    return ("dropped", {"type": "session_meta", "payload": {
        "id": "00000000-0000-4000-8000-000000000000",
        "cwd": cwd,
        "originator": "codex_cli",
        "cli_version": "0.0.0",
        "instructions": "<base instructions omitted for fixture>",
    }})


def TS():
    return ("dropped", {"type": "event_msg", "payload": {"type": "task_started", "model_context_window": 200000}})


def TCDONE():
    return ("dropped", {"type": "event_msg", "payload": {"type": "task_complete", "last_agent_message": ""}})


def TCOUNT():
    return ("dropped", {"type": "event_msg", "payload": {"type": "token_count", "info": {"total_token_usage": {"total_tokens": 1234}}}})


def TURNCTX():
    return ("dropped", {"type": "turn_context", "payload": {"model": "acme-model-1", "sandbox_policy": "workspace-write", "approval_policy": "on-request"}})


def DEV(text=DEV_BOILERPLATE):
    return ("dropped", {"type": "response_item", "payload": {
        "type": "message", "role": "developer",
        "content": [{"type": "input_text", "text": text}],
    }})


def REASON(text):
    return ("dropped", {"type": "response_item", "payload": {
        "type": "reasoning",
        "content": [{"type": "reasoning_text", "text": text}],
    }})


def UMIRROR(text):
    return ("dropped", {"type": "event_msg", "payload": {"type": "user_message", "message": text}})


def AMIRROR(text):
    return ("dropped", {"type": "event_msg", "payload": {"type": "agent_message", "message": text}})


def RMIRROR(text):
    return ("dropped", {"type": "event_msg", "payload": {"type": "agent_reasoning", "text": text}})


def U(text):
    return ("kept", {"type": "response_item", "payload": {
        "type": "message", "role": "user",
        "content": [{"type": "input_text", "text": text}],
    }})


def A(text):
    return ("kept", {"type": "response_item", "payload": {
        "type": "message", "role": "assistant",
        "content": [{"type": "output_text", "text": text}],
    }})


def CALL(name, args_obj, cid="call_x"):
    return ("kept", {"type": "response_item", "payload": {
        "type": "function_call",
        "name": name,
        "arguments": json.dumps(args_obj, ensure_ascii=False),
        "call_id": cid,
    }})


def OUT(output_text, cid="call_x"):
    return ("kept", {"type": "response_item", "payload": {
        "type": "function_call_output",
        "call_id": cid,
        "output": output_text,
    }})


def BOUND(message):
    return ("boundary", {"type": "compacted", "payload": {"message": message}})


def env(output, code=0, tokens=128, chunk="a1b2c3", wall="0.04"):
    """Wrap command output in the real codex exec_command envelope (anchors §5.3)."""
    return (
        "Chunk ID: {chunk}\nWall time: {wall} seconds\n"
        "Process exited with code {code}\nOriginal token count: {tokens}\nOutput:\n{out}"
    ).format(chunk=chunk, wall=wall, code=code, tokens=tokens, out=output)


# Convenience combinators (keep dropped-noise realistic per anchors §5.1 mirror caveat).
def first_user(text):
    return [TS(), DEV(), U(text), TURNCTX(), UMIRROR(text)]


def user(text):
    return [TS(), U(text), TURNCTX(), UMIRROR(text)]


def asst(text):
    return [A(text), AMIRROR(text)]


def close():
    return [TCOUNT(), TCDONE()]


# =====================================================================
# 3. CASES — Phase 1 (14 cases). Each: id, dirname, uuid, iso, cwd, lines.
#    The .jsonl lives at cases/<dirname>/rollout-<iso>-<uuid>.jsonl.
#    UUIDs are hex-only (is_uuid_form) and encode the case number.
# =====================================================================

def build_cases():
    cases = []

    # ---- C001 — decision: session store -> Postgres (canonical / §7 sanity) ----
    cases.append({
        "id": "C001",
        "dirname": "C001-pg-session-store",
        "uuid": "0000c001-0000-4000-8000-00000000c001",
        "iso": "2026-05-10T09-00-00",
        "cwd": "/Users/USER/code/acmechat",
        "lines": [
            SM("/Users/USER/code/acmechat"),
            *first_user("我们 AcmeChat 服务的会话状态(session state)现在塞在进程内存里,一重启全丢。该换个持久化方案了,你看用什么存?"),
            *asst("先排除继续用内存——重启丢数据,多实例也不共享。要持久化。我看候选是 Postgres,或者直接落本地 SQLite 文件。我先确认下环境里有没有现成的 Postgres。"),
            CALL("exec_command", {"cmd": "psql --version"}, cid="c1"),
            OUT(env("psql (PostgreSQL) 15.4"), cid="c1"),
            *asst("环境里已经有 Postgres 15。这里有两个硬约束:一是会话写入要和用户余额扣减放在同一个事务里提交,需要 ACID 保证;二是后面要按租户做规模化的聚合查询,SQLite 单文件在并发写和扩展上扛不住。所以我建议定 Postgres,不用 SQLite。"),
            *close(),
            *user("行,那就 Postgres。"),
            *asst("好,会话状态落 Postgres,我建一张 sessions 表,写入和余额扣减共用一个事务。"),
            *close(),
        ],
    })

    # ---- C002 — decision: session store -> Redis (contradiction partner of C001) ----
    cases.append({
        "id": "C002",
        "dirname": "C002-redis-session-store",
        "uuid": "0000c002-0000-4000-8000-00000000c002",
        "iso": "2026-05-10T11-00-00",
        "cwd": "/Users/USER/code/acmechat",
        "lines": [
            SM("/Users/USER/code/acmechat"),
            *first_user("AcmeChat 的会话状态(session)到底存哪?要求是读写要快,而且过期的会话能自动清掉,别让我写定时清理任务。"),
            *asst("会话读写在热路径上,每个请求都要碰一次,优先级是低延迟。候选就两个:进程内存 map,或者 Redis。内存 map 多实例之间不共享、重启也丢。Redis 跨实例共享,而且能用 TTL 让会话到期自动过期,正好省掉清理任务。所以这里定 Redis。"),
            *asst("具体方案:key 用 session:<id>,value 存序列化后的会话对象,统一设 30 分钟 TTL,续期就重设 TTL。"),
            *close(),
            *user("可以,就 Redis。"),
            *asst("好,会话状态走 Redis,session:<id> + 30 分钟 TTL。"),
            *close(),
        ],
    })

    # ---- C003 — failure: flaky tests from a shared /tmp path (noisy tool output) ----
    flaky_output = (
        "   Compiling acme-store v0.3.1\n"
        "   Compiling acme-store-tests v0.3.1\n"
        "warning: unused variable: `ctx`\n"
        "    Finished test [unoptimized] target(s) in 4.21s\n"
        "     Running tests/store.rs\n"
        "running 12 tests\n"
        "test reads::test_lookup ... ok\n"
        "test writes::test_append ... ok\n"
        "test writes::test_writer ... FAILED\n"
        "test reads::test_reader ... FAILED\n"
        "test reads::test_scan ... ok\n\n"
        "failures:\n\n"
        "---- writes::test_writer stdout ----\n"
        "thread 'writes::test_writer' panicked at 'assertion failed: `(left == right)`\n"
        "  left: `7`,\n right: `0`', tests/store.rs:88\n"
        "note: both test_writer and test_reader open the SAME path /tmp/acme-fixture.db\n"
        "---- reads::test_reader stdout ----\n"
        "thread 'reads::test_reader' panicked at 'database is locked', tests/store.rs:142\n\n"
        "test result: FAILED. 10 passed; 2 failed"
    )
    cases.append({
        "id": "C003",
        "dirname": "C003-flaky-shared-tmpdir",
        "uuid": "0000c003-0000-4000-8000-00000000c003",
        "iso": "2026-05-11T14-30-00",
        "cwd": "/Users/USER/code/acme-store",
        "lines": [
            SM("/Users/USER/code/acme-store"),
            *first_user("cargo test 偶尔挂,CI 上挂得更频繁,本地单个跑又每次都过。帮我看下到底咋回事。"),
            *asst("本地过、CI 挂、概率性失败——典型的 flaky test,八成是测试之间共享了状态。我并行多跑几次复现一下。"),
            CALL("exec_command", {"cmd": "cargo test --jobs 8"}, cid="c1"),
            OUT(env(flaky_output, code=101, tokens=512), cid="c1"),
            *asst("复现了,根因找到了:test_writer 和 test_reader 都打开同一个写死的路径 /tmp/acme-fixture.db,并行跑的时候互相踩,一个 assert 失败、一个报 database is locked。串行(你本地单跑)时它们错开了所以不复现。修法是每个测试用 tempfile::tempdir() 建自己的独立临时目录,别再共享 /tmp 下的固定路径。我改完并行 8 线程连跑 50 次,全绿。"),
            *close(),
        ],
    })

    # ---- C004 — failure: CORS preflight strips Authorization (pure-en) ----
    cors_output = (
        "HTTP/1.1 401 Unauthorized\n"
        "Date: Mon, 12 May 2026 08:00:00 GMT\n"
        "Content-Type: application/json\n"
        "Vary: Origin\n"
        "Access-Control-Allow-Origin: https://app.acme.local\n"
        "Access-Control-Allow-Methods: GET, POST, OPTIONS\n"
        "Access-Control-Allow-Headers: Content-Type\n"
        "Content-Length: 27\n\n"
        '{"error":"missing token"}'
    )
    cases.append({
        "id": "C004",
        "dirname": "C004-cors-preflight-auth",
        "uuid": "0000c004-0000-4000-8000-00000000c004",
        "iso": "2026-05-12T08-00-00",
        "cwd": "/Users/USER/code/acme-api",
        "lines": [
            SM("/Users/USER/code/acme-api"),
            *first_user("Our web client gets a 401 on every cross-origin API call, but the same token works fine from curl. What's going on?"),
            *asst("Browser-only 401 but curl works points at a CORS preflight problem: the browser fires an OPTIONS preflight before the real request. Let me inspect what the proxy returns for that preflight."),
            CALL("exec_command", {"cmd": "curl -i -X OPTIONS https://api.acme.local/v1/orders -H 'Origin: https://app.acme.local' -H 'Access-Control-Request-Method: POST'"}, cid="c1"),
            OUT(env(cors_output, code=0, tokens=200), cid="c1"),
            *asst("Found it. Two compounding problems. (1) The OPTIONS preflight is hitting our auth middleware and getting a 401, because browsers never send the Authorization header on a preflight — the middleware runs before the CORS handler, so the preflight dies. (2) Even if it passed, the response's Access-Control-Allow-Headers only lists Content-Type, not Authorization, so the browser would refuse to send the token on the real request. Fix: short-circuit OPTIONS before the auth middleware and add Authorization to Access-Control-Allow-Headers. After that the browser completes the preflight and sends the real request with the token, which 200s."),
            *close(),
        ],
    })

    # ---- C005 — pattern: registering a Tauri command (codebase idiom) ----
    rg_output = (
        "src-tauri/src/commands/audit.rs:14:#[tauri::command]\n"
        "src-tauri/src/commands/audit.rs:15:pub fn export_audit_log(path: String) -> Result<(), String> {\n"
    )
    cases.append({
        "id": "C005",
        "dirname": "C005-tauri-command-registration",
        "uuid": "0000c005-0000-4000-8000-00000000c005",
        "iso": "2026-05-13T10-15-00",
        "cwd": "/Users/USER/code/acme-desktop",
        "lines": [
            SM("/Users/USER/code/acme-desktop"),
            *first_user("我加了个新的 Tauri command export_audit_log,前端 invoke 的时候报 'command export_audit_log not found'。"),
            *asst("这个仓库加 command 有个固定套路,漏一步前端就 invoke 不到。我先看下你这个函数都被引用在哪。"),
            CALL("exec_command", {"cmd": "rg -n 'export_audit_log' src-tauri/src CodexMonitor/src"}, cid="c1"),
            OUT(env(rg_output, tokens=90), cid="c1"),
            *asst("原因清楚了:你只写了 #[tauri::command] 的函数定义,但没注册。本仓库的约定是两处都要改,缺一不可:(1) 在 src-tauri/src/main.rs 的 tauri::generate_handler![...] 宏里把 export_audit_log 加进去,运行时才会挂上这个 command;(2) 在 CodexMonitor/src/bindings.ts 里补一个对应的包装函数,前端才有类型、才能 invoke。两处都补上就通了。"),
            *user("原来要改两个地方,记下了。"),
            *asst("对,这就是本仓库加 command 的固定模式:generate_handler! 宏注册 + bindings.ts 暴露 TS 类型,两边必须同步。"),
            *close(),
        ],
    })

    # ---- C006 — fact: readiness vs liveness probe paths (utf8 / emoji) ----
    healthz_output = (
        "services/acme-queue/src/routes.rs:31:    router.get(\"/livez\", liveness);   // process alive -> 200\n"
        "services/acme-queue/src/routes.rs:32:    router.get(\"/healthz\", readiness); // 200 ONLY after DB pool connected, else 503\n"
    )
    cases.append({
        "id": "C006",
        "dirname": "C006-readiness-healthz",
        "uuid": "0000c006-0000-4000-8000-00000000c006",
        "iso": "2026-05-14T16-45-00",
        "cwd": "/Users/USER/code/acme-queue",
        "lines": [
            SM("/Users/USER/code/acme-queue"),
            *first_user("部署 AcmeQueue 的时候 k8s 老是反复重启它 🤔 这个服务的健康检查到底有哪几个路由,该怎么配?"),
            *asst("我搜下这个服务暴露了哪些健康检查路由,再看它们各自的语义。"),
            CALL("exec_command", {"cmd": "rg -n 'healthz|livez|ready' services/acme-queue/src"}, cid="c1"),
            OUT(env(healthz_output, tokens=110), cid="c1"),
            *asst("查到了 ✅。AcmeQueue 有两个探针,语义不一样:/livez 是 liveness,进程活着就返回 200;/healthz 是 readiness,只有在 DB 连接池建立之后才返回 200,否则返回 503。你的反复重启八成是把 livenessProbe 指到了 /healthz——DB 还没连上时 /healthz 返回 503,liveness 就把进程杀了重启。正确配法:readinessProbe 指 /healthz,livenessProbe 指 /livez。"),
            *close(),
        ],
    })

    # ---- C007 — fact: where the DB connection string comes from (noisy output) ----
    config_output = (
        "acme-api config (resolved):\n"
        "  log.level            <- env ACME_LOG (unset) -> default \"info\"\n"
        "  server.worker_threads<- env ACME_WORKERS (unset) -> default 8\n"
        "  server.bind          -> 0.0.0.0:8080\n"
        "  telemetry.otlp       <- env ACME_OTLP (unset) -> default disabled\n"
        "  feature.new_inbox    -> false\n"
        "  feature.audit_trail  -> true\n"
        "  db.url               <- env ACME_DB_URL (unset) -> default \"postgres://localhost:5432/acme_dev\"\n"
        "  db.pool_size         <- env ACME_DB_POOL (unset) -> default 10\n"
        "  cache.ttl_secs       -> 60\n"
    )
    cases.append({
        "id": "C007",
        "dirname": "C007-db-url-env-var",
        "uuid": "0000c007-0000-4000-8000-00000000c007",
        "iso": "2026-05-15T09-20-00",
        "cwd": "/Users/USER/code/acme-api",
        "lines": [
            SM("/Users/USER/code/acme-api"),
            *first_user("acme-api 的 Postgres 连接串是从哪儿配的?我想在 CI 里覆盖它,不想改代码。"),
            *asst("我 dump 一下它启动时解析出来的配置,看连接串走的哪个来源。"),
            CALL("exec_command", {"cmd": "./acme-api --print-config"}, cid="c1"),
            OUT(env(config_output, tokens=260), cid="c1"),
            *asst("看到了:db.url 从环境变量 ACME_DB_URL 读;没设这个变量时回退到默认 postgres://localhost:5432/acme_dev。所以你在 CI 里 export ACME_DB_URL=... 就能覆盖连接串,完全不用动代码。"),
            *close(),
        ],
    })

    # ---- C008 — reverse: greeting-only (No-Echo / Skip-trivial; mirrors prompt Example 3) ----
    cases.append({
        "id": "C008",
        "dirname": "C008-greeting-only",
        "uuid": "0000c008-0000-4000-8000-00000000c008",
        "iso": "2026-05-16T12-00-00",
        "cwd": "/Users/USER/code/PROJECT",
        "lines": [
            SM(),
            *first_user("thanks, that fixed it!"),
            *asst("Glad it worked — happy to help anytime."),
            *close(),
        ],
    })

    # ---- C009 — reverse: rote task, no durable lesson (Skip-trivial / No-Echo) ----
    rename_output = (
        "renamed 'getting started.md' -> 'getting-started.md'\n"
        "renamed 'api reference.md' -> 'api-reference.md'\n"
        "renamed 'team notes.md' -> 'team-notes.md'\n"
        "done: 3 files"
    )
    cases.append({
        "id": "C009",
        "dirname": "C009-rote-rename",
        "uuid": "0000c009-0000-4000-8000-00000000c009",
        "iso": "2026-05-17T11-05-00",
        "cwd": "/Users/USER/code/acme-docs",
        "lines": [
            SM("/Users/USER/code/acme-docs"),
            *first_user("把 docs 目录下所有 markdown 文件名里的空格换成连字符。"),
            *asst("好的,我来批量重命名。"),
            CALL("exec_command", {"cmd": "cd docs && for f in *\\ *.md; do mv \"$f\" \"${f// /-}\"; done"}, cid="c1"),
            OUT(env(rename_output, tokens=70), cid="c1"),
            *asst("改完了,一共重命名了 3 个文件,都成功了。"),
            *close(),
        ],
    })

    # ---- C010 — reverse: chitchat / help request with no substance ----
    cases.append({
        "id": "C010",
        "dirname": "C010-chitchat",
        "uuid": "0000c010-0000-4000-8000-00000000c010",
        "iso": "2026-05-18T13-40-00",
        "cwd": "/Users/USER/code/PROJECT",
        "lines": [
            SM(),
            *first_user("在吗?想问个事。"),
            *asst("在的,你说。"),
            *user("就是想确认下你能不能帮我看代码。"),
            *asst("可以的,把你想看的部分发我,或者告诉我文件路径就行。"),
            *close(),
        ],
    })

    # ---- C011 — reverse: aborted mid-exploration, no conclusion ----
    cases.append({
        "id": "C011",
        "dirname": "C011-aborted-cache",
        "uuid": "0000c011-0000-4000-8000-00000000c011",
        "iso": "2026-05-19T15-10-00",
        "cwd": "/Users/USER/code/acme-api",
        "lines": [
            SM("/Users/USER/code/acme-api"),
            *first_user("我在想要不要给订单接口加个本地缓存层…"),
            *asst("可以聊聊。要不要先确认下这个接口的读写比和一致性要求?另外可以先压一遍,看有没有明显热点再决定。"),
            *user("等下,我先去开个会,这个待会儿再聊。"),
            *asst("好,随时继续。"),
            *close(),
        ],
    })

    # ---- C012 — multi-segment-compaction + with-prior-summary; supersede-shaped ----
    # Segment 1: rote env setup (0 KP). Boundary carries a tempting "BlueFin" fact.
    # Segment 2: a real decision (exponential backoff). Assert the KP does NOT leak
    # the prior-summary-only "BlueFin" fact -> proves prior_summary is not extracted.
    make_output = "make: dependencies installed\nBuild succeeded in 12.3s"
    prior = (
        "Earlier in this thread the team set up the dev environment for the project "
        "(codename BlueFin, repo acme/bluefin), installed dependencies and confirmed a "
        "clean local build. No design or architecture decisions were made yet."
    )
    cases.append({
        "id": "C012",
        "dirname": "C012-compaction-backoff",
        "uuid": "0000c012-0000-4000-8000-00000000c012",
        "iso": "2026-05-20T09-00-00",
        "cwd": "/Users/USER/code/bluefin",
        "lines": [
            # --- segment 1 (pre-boundary): rote setup, expect 0 KP ---
            SM("/Users/USER/code/bluefin"),
            *first_user("先把开发环境跑起来,我本地能 build 就行。"),
            *asst("好,我装依赖然后 build 一下。"),
            CALL("exec_command", {"cmd": "make setup && make build"}, cid="c1"),
            OUT(env(make_output, tokens=80), cid="c1"),
            *asst("环境 OK,依赖装好了,本地能正常 build。"),
            *close(),
            # --- compaction boundary ---
            BOUND(prior),
            # --- segment 2 (post-boundary): real decision, expect 1 KP ---
            *user("现在的重试策略是固定 1 秒重试,生产上下游一抖动就同步重试、直接雪崩。改一下。"),
            *asst("固定间隔重试在下游抖动时会让所有客户端同步重试、放大冲击。换成指数退避加抖动(exponential backoff with jitter):基数 100ms,每次失败翻倍,上限 10s,再叠加随机 jitter 把重试时刻打散。这样下游恢复期不会被同时涌入的重试打爆。"),
            *user("可以,就这么改。"),
            *asst("好,重试改成指数退避 + jitter,基数 100ms、上限 10s,替掉原来的固定 1 秒。"),
            *close(),
        ],
    })

    # ---- C013 — all-dropped: no Kept line at all; distill must return [] ----
    cases.append({
        "id": "C013",
        "dirname": "C013-all-dropped",
        "uuid": "0000c013-0000-4000-8000-00000000c013",
        "iso": "2026-05-21T10-00-00",
        "cwd": "/Users/USER/code/PROJECT",
        "lines": [
            SM(),
            TS(),
            DEV(),
            TURNCTX(),
            REASON("用户没有给出实质任务,只是环境初始化,我不需要回复实质内容。"),
            RMIRROR("用户没有给出实质任务。"),
            TCOUNT(),
            TCDONE(),
        ],
    })

    # ---- C014 — decision: day.js over moment.js (mixed-zh-en) ----
    cases.append({
        "id": "C014",
        "dirname": "C014-dayjs-over-moment",
        "uuid": "0000c014-0000-4000-8000-00000000c014",
        "iso": "2026-05-22T14-25-00",
        "cwd": "/Users/USER/code/acme-web",
        "lines": [
            SM("/Users/USER/code/acme-web"),
            *first_user("前端处理时间这块,我们继续用 moment 还是换别的?现在打包体积有点大。"),
            *asst("建议换掉 moment。理由:moment.js 官方已经进入维护模式(deprecated),不推荐新功能再用;而且它体积大、不支持 tree-shaking,是你包变大的一个来源。day.js 的 API 跟 moment 基本兼容,gzip 后 2KB 左右,按需加载插件。所以选 day.js。"),
            *user("那时间处理统一换成 day.js。"),
            *asst("好,时间处理统一用 day.js,逐步替掉 moment。"),
            *close(),
        ],
    })

    return cases


# =====================================================================
# 4. Engine: write jsonl, compute expected_ingest, render, verify.
# =====================================================================

def case_jsonl_path(case):
    d = os.path.join(CASES_DIR, case["dirname"])
    return os.path.join(d, "rollout-{}-{}.jsonl".format(case["iso"], case["uuid"]))


def render_lines(case):
    """Return list of (line_no, intended_cls, payload_str) with cosmetic timestamps."""
    out = []
    iso = case["iso"].replace("-", ":", 0)  # keep cosmetic
    # Build a base prefix like 2026-05-10T09:00:00 from the iso (dashes in time -> colons).
    date_part, _, time_part = case["iso"].partition("T")
    time_colon = time_part.replace("-", ":")
    base = "{}T{}".format(date_part, time_colon)
    for i, (cls, payload) in enumerate(case["lines"], start=1):
        ts = "{}.{:03d}Z".format(base, i)
        line_obj = {"timestamp": ts}
        line_obj.update(payload)
        s = json.dumps(line_obj, ensure_ascii=False)
        out.append((i, cls, s))
    return out


def self_check(case, lines):
    problems = []
    for (no, intended, payload_str) in lines:
        actual, _ = parse_line(payload_str)
        if actual != intended:
            problems.append("  L{}: intended={} but parse_line={} :: {}".format(
                no, intended, actual, payload_str[:120]))
    return problems


def compute_ingest(lines):
    kept, dropped, boundary = [], [], []
    for (no, _intended, payload_str) in lines:
        cls, _ = parse_line(payload_str)
        if cls == "kept":
            kept.append(no)
        elif cls == "boundary":
            boundary.append(no)
        else:
            dropped.append(no)
    return {
        "raw_event_count": len(lines),
        "kept_line_nos": kept,
        "dropped_line_nos": dropped,
        "boundary_line_nos": boundary,
    }


def cmd_gen():
    cases = build_cases()
    total = 0
    for case in cases:
        lines = render_lines(case)
        problems = self_check(case, lines)
        if problems:
            print("SELF-CHECK FAILED for {} ({}):".format(case["id"], case["dirname"]))
            print("\n".join(problems))
            sys.exit(1)
        path = case_jsonl_path(case)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        body = "\n".join(s for (_n, _c, s) in lines) + "\n"
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(body)
        ing = compute_ingest(lines)
        segs = segment_thread([(n, s) for (n, _c, s) in lines])
        maxlen = max((len(sg["transcript"]) for sg in segs), default=0)
        total += 1
        print("[gen] {} -> {}".format(case["id"], os.path.relpath(path, CASES_DIR)))
        print("       raw_event_count={} kept={} boundary={} segments={} max_transcript_chars={}".format(
            ing["raw_event_count"], ing["kept_line_nos"], ing["boundary_line_nos"], len(segs), maxlen))
    print("\n[gen] self-check OK for all {} cases. Run `verify --fix` to sync expected_ingest into the yamls.".format(total))


def _fmt_list(xs):
    return "[" + ", ".join(str(x) for x in xs) + "]"


def ingest_block_text(ing):
    return (
        "{start}\n"
        "expected_ingest:\n"
        "  raw_event_count: {n}\n"
        "  kept_line_nos: {kept}\n"
        "  dropped_line_nos: {dropped}\n"
        "  boundary_line_nos: {boundary}\n"
        "{end}"
    ).format(
        start=ING_START, end=ING_END,
        n=ing["raw_event_count"],
        kept=_fmt_list(ing["kept_line_nos"]),
        dropped=_fmt_list(ing["dropped_line_nos"]),
        boundary=_fmt_list(ing["boundary_line_nos"]),
    )


def _parse_int_list(s):
    s = s.strip()
    if s.startswith("[") and s.endswith("]"):
        s = s[1:-1]
    s = s.strip()
    if not s:
        return []
    return [int(x) for x in s.split(",")]


def parse_yaml_ingest_region(text):
    """Extract the expected_ingest values from inside the sentinel region.
    Returns dict or None if region/fields missing."""
    if ING_START not in text or ING_END not in text:
        return None
    region = text.split(ING_START, 1)[1].split(ING_END, 1)[0]
    out = {}
    m = re.search(r"raw_event_count:\s*(\d+)", region)
    if m:
        out["raw_event_count"] = int(m.group(1))
    for key in ("kept_line_nos", "dropped_line_nos", "boundary_line_nos"):
        m = re.search(key + r":\s*(\[[^\]]*\])", region)
        if m:
            out[key] = _parse_int_list(m.group(1))
    needed = {"raw_event_count", "kept_line_nos", "dropped_line_nos", "boundary_line_nos"}
    if not needed.issubset(out.keys()):
        return None
    return out


def cmd_verify(fix=False, only=None):
    cases = build_cases()
    n_pass = n_fail = n_fix = 0
    for case in cases:
        if only and case["id"] != only:
            continue
        lines = render_lines(case)
        problems = self_check(case, lines)
        if problems:
            print("SELF-CHECK FAILED for {}:".format(case["id"]))
            print("\n".join(problems))
            n_fail += 1
            continue
        truth = compute_ingest(lines)
        gt_path = os.path.join(CASES_DIR, case["dirname"], "ground_truth.yaml")
        if not os.path.exists(gt_path):
            print("[verify] {} : ground_truth.yaml MISSING".format(case["id"]))
            n_fail += 1
            continue
        with open(gt_path, "r", encoding="utf-8") as f:
            text = f.read()
        if fix:
            if ING_START in text and ING_END in text:
                before = text.split(ING_START, 1)[0]
                after = text.split(ING_END, 1)[1]
                text = before + ingest_block_text(truth) + after
                with open(gt_path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(text)
                print("[verify --fix] {} : expected_ingest synced".format(case["id"]))
                n_fix += 1
                continue
            else:
                print("[verify --fix] {} : sentinel region MISSING — add the markers first".format(case["id"]))
                n_fail += 1
                continue
        got = parse_yaml_ingest_region(text)
        if got is None:
            print("[verify] {} : expected_ingest region unreadable (run with --fix)".format(case["id"]))
            n_fail += 1
            continue
        ok = (got["raw_event_count"] == truth["raw_event_count"]
              and got["kept_line_nos"] == truth["kept_line_nos"]
              and got["dropped_line_nos"] == truth["dropped_line_nos"]
              and got["boundary_line_nos"] == truth["boundary_line_nos"])
        if ok:
            print("[verify] {} : PASS (raw={}, kept={}, boundary={})".format(
                case["id"], truth["raw_event_count"], truth["kept_line_nos"], truth["boundary_line_nos"]))
            n_pass += 1
        else:
            print("[verify] {} : FAIL".format(case["id"]))
            print("    yaml : {}".format(got))
            print("    truth: {}".format(truth))
            n_fail += 1
    print("\n[verify] pass={} fail={} fixed={}".format(n_pass, n_fail, n_fix))
    if n_fail:
        sys.exit(1)


def cmd_transcript(case_id):
    cases = build_cases()
    for case in cases:
        if case["id"] != case_id:
            continue
        lines = render_lines(case)
        segs = segment_thread([(n, s) for (n, _c, s) in lines])
        print("=== {} {} ===".format(case["id"], case["dirname"]))
        for i, sg in enumerate(segs, start=1):
            print("--- segment {} (lines {}..{}) prior_summary={} ---".format(
                i, sg["start"], sg["end"],
                repr(sg["prior_summary"]) if sg["prior_summary"] is not None else "None"))
            print(sg["transcript"])
            print("[chars={}]".format(len(sg["transcript"])))
        return
    print("no such case: {}".format(case_id))
    sys.exit(1)


def main():
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        sys.exit(0)
    cmd = args[0]
    if cmd == "gen":
        cmd_gen()
    elif cmd == "verify":
        fix = "--fix" in args[1:]
        only = None
        for a in args[1:]:
            if not a.startswith("-"):
                only = a
        cmd_verify(fix=fix, only=only)
    elif cmd == "transcript":
        if len(args) < 2:
            print("usage: corpus_tool.py transcript <CASE_ID>")
            sys.exit(1)
        cmd_transcript(args[1])
    else:
        print("unknown command: {}".format(cmd))
        print(__doc__)
        sys.exit(1)


if __name__ == "__main__":
    main()
